name: Test
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 job01:
   if: contains(github.event.comment.html_url, '/pull/')
   runs-on: ubuntu-latest
   steps:
     - name: Clone git repo
       if: contains(github.event.comment.body, '/deploy')
       uses: actions/checkout@v2   
     - name: checkout
       id: checkout_step
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       if: contains(github.event.comment.body, '/deploy')
       run: |
         PR_URL="${{ github.event.issue.pull_request.url }}"
         PR_NUM=${PR_URL##*/}
         echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
         hub pr checkout $PR_NUM
         echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"
     - name: Test repo
       run: |
        echo "Pull request's base branch is: ${{steps.checkout_step.outputs.branch}}"