name: Cypress Integration Test
on: push
jobs:
  cypress-chrome:
    runs-on: ubuntu-16.04
    name: Testing Chrome
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
      
      - name: Generate Mochawesome Report
        if: always()
        run: yarn report:init && yarn report:gen

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-edge-report
          path: cypress/reports