name: Edge
on: push
jobs:
  edge:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: edge
      
      - if: always()
      - name: Generate Mochawesome Report
      - run: yarn combine-reports && yarn run generate-report

      - if: always()
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-edge-report
          path: cypress/reports

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-edge-videos
          path: cypress/videos
