name: Edge
on: push
jobs:
  edge:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: edge
      - uses: actions/upload-artifact@v2
        with:
          name: cypress-edge
          path: /cypress

  chrome:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
      - uses: actions/upload-artifact@v2
        with:
          name: cypress-chrome
          path: /cypress
     