name: Testing
on: push
jobs:
  Cypress:
    runs-on: ubuntu-latest
  
    name: Testing Chrome
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
      
      - name: Generate Mochawesome Report
        if: always()
        run: yarn report:gen

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-report
          path: cypress/reports