name: Cypress Integration Test
on: push
jobs:
  cypress-chrome:
    runs-on: ubuntu-16.04
    name: Testing Chrome
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
      
      - name: Generate Mochawesome Report
        if: always()
        run: mkdir cypress/reports/mochareports && yarn combine-reports && yarn run generate-report

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-edge-report
          path: cypress/reports

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-edge-videos
          path: cypress/videos
