name: Testing
on: push
jobs:
  Cypress Integration Test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001

    name: Testing Firefox & Chrome
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        if: always()
        with:
          browser: chrome
      
      - uses: cypress-io/github-action@v2
        if: always()
        with:
          browser: firefox

      - name: Generate Mochawesome Report
        if: always()
        run: yarn report:gen

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-report
          path: cypress/reports