name: Test
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 job01:
   if: contains(github.event.comment.html_url, '/pull/')
   runs-on: ubuntu-latest
   steps:
     - name: say hello
       if: contains(github.event.comment.body, '/deploy')
       run: |
         echo "this is ${{ github.event.pull_request.head.sha }}"