name: Test
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 job01:
   if: contains(github.event.comment.html_url, '/pull/')
   runs-on: ubuntu-latest
   steps:
     - name: Clone git repo
       if: contains(github.event.comment.body, '/deploy')
       uses: actions/checkout@v2

     - name: say hello
       if: contains(github.event.comment.body, '/deploy')
       run: |
         PR_URL="${{ github.event.issue.pull_request.url }}"
         PR_NUM=${PR_URL##*/}
         echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
         hub pr checkout $PR_NUM