name: Testing
on:
  pull_request:
    branches:
      - master

jobs:
  Cypress:
    runs-on: ubuntu-latest
  
    name: Testing Chrome
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          working-directory: packages/sites
          browser: chrome
      
      - name: Generate Mochawesome Report
        if: always()
        working-directory: packages/sites
        run: node ./mochawesome-report-generator.js

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-report
          path: packages/sites/cypress/reports