name: Test
on:
  issue_comment:
    types: [created]
jobs:
  example:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Execute for pull request comments only
        if: contains(github.event.issue.body, '/deploy')
        run: echo "This is Branch ${{github.event.issue.pull_request.base.ref}}"